/**
 * Comment-preserving YAML refresh for DynamoDB table definitions.
 *
 * Requirements addressed:
 * - Preserve all non-generated Properties and comments in tables/NNN/table.yml.
 * - Overwrite only the generated sections:
 *   • Properties.AttributeDefinitions
 *   • Properties.KeySchema
 *   • Properties.GlobalSecondaryIndexes
 * - Apply managed table properties deterministically when configured:
 *   • Properties.BillingMode
 *   • Properties.ProvisionedThroughput
 *   • Properties.TableName
 * - Compose a new table.yml from baseline when no file exists yet.
 */

import { promises as fs } from 'node:fs';
import { resolve } from 'node:path';

import type { CreateTableCommandInput } from '@aws-sdk/client-dynamodb';
import type {
  BaseConfigMap,
  EntityManager,
} from '@karmaniverous/entity-manager';
import YAML, { type Document, type YAMLMap } from 'yaml';

import { generateTableDefinition } from '../Tables/generateTableDefinition';
import type { ManagedTablePropertiesInfo } from './tableProperties';
import { assertManagedTablePropertiesInvariants } from './tableProperties';

type TableDoc = Document;

const HEADER_COMMENT = [
  'GENERATED SECTIONS WARNING',
  '',
  '- The following Properties keys are regenerated by tooling:',
  '  • AttributeDefinitions',
  '  • KeySchema',
  '  • GlobalSecondaryIndexes',
  '',
  '- Edit non-generated Properties (e.g., BillingMode, TTL, PITR, Streams, SSE, Tags) in this file',
  '  or in tables/table.template.yml and re-run generate-table-definition.',
  '',
  '- Use validate-table-definition to detect drift against the EntityManager config.',
].join('\n');

function ensureTableDoc(): TableDoc {
  const doc = new YAML.Document();
  doc.commentBefore = HEADER_COMMENT;
  doc.set('Type', 'AWS::DynamoDB::Table');
  // Ensure Properties is a YAMLMap (not a plain object)
  doc.set('Properties', doc.createNode({}));
  return doc;
}

function getPropsNode(doc: TableDoc): YAMLMap {
  let props = doc.get('Properties');
  // Reset to an empty mapping if missing/unexpected
  if (
    !props ||
    typeof props !== 'object' ||
    !('set' in (props as Record<string, unknown>))
  ) {
    // Ensure we create a YAMLMap
    doc.set('Properties', doc.createNode({}));
    props = doc.get('Properties');
  }
  return props as YAMLMap;
}

/** Replace a child under Properties (preserving other nodes/comments). */
function setPropsChild(doc: TableDoc, key: string, value: unknown) {
  const props = getPropsNode(doc);
  // The doc API preserves sibling nodes and their comments automatically.
  // We only replace the specified key.
  props.set(key, value);
}

/**
 * Generated table-definition sections (subset of DynamoDB CreateTableCommandInput).
 *
 * @category get-dotenv
 */
export interface GeneratedSections {
  /** Generated `Properties.AttributeDefinitions`. */
  AttributeDefinitions?: CreateTableCommandInput['AttributeDefinitions'];
  /** Generated `Properties.KeySchema`. */
  KeySchema?: CreateTableCommandInput['KeySchema'];
  /** Generated `Properties.GlobalSecondaryIndexes`. */
  GlobalSecondaryIndexes?: CreateTableCommandInput['GlobalSecondaryIndexes'];
}

/**
 * Optional overlays applied when composing a new table.yml (creation-time helper).
 *
 * @category get-dotenv
 */
export interface OverlayOptions {
  /** Optional BillingMode for initial composition (no-op on refresh unless caller wants to change it). */
  BillingMode?: CreateTableCommandInput['BillingMode'];
  /** Provisioned throughput (RCU/WCU) if using PROVISIONED (initial composition helper). */
  ProvisionedThroughput?: CreateTableCommandInput['ProvisionedThroughput'];
  /** Optional one-off TableName override for creation-time plumbing (not persisted here). */
  TableName?: string;
}

function toPlainPropertiesNode(value: unknown): Record<string, unknown> {
  // Re-emit via YAML to ensure a plain JS object (handles YAMLMap/Seq)
  return YAML.parse(YAML.stringify(value ?? {})) as Record<string, unknown>;
}

function applyManagedTableProperties(
  doc: TableDoc,
  info?: ManagedTablePropertiesInfo,
): void {
  if (!info) return;
  const props = getPropsNode(doc);
  const m = info.managed;

  if (info.manages.billingMode && m.BillingMode !== undefined) {
    props.set('BillingMode', m.BillingMode);
  }
  if (info.manages.provisionedThroughput && m.ProvisionedThroughput) {
    props.set('ProvisionedThroughput', m.ProvisionedThroughput);
  }
  if (info.manages.tableName && m.TableName) {
    props.set('TableName', m.TableName);
  }

  // Validate invariants implied by managed props against the effective YAML.
  const effectiveProps = toPlainPropertiesNode(props);
  assertManagedTablePropertiesInvariants({
    info,
    effectiveProperties: effectiveProps,
  });
}

/** Load YAML as a CST-backed Document if file exists; otherwise return undefined. */
async function loadDoc(filePath: string): Promise<TableDoc | undefined> {
  try {
    const src = await fs.readFile(filePath, 'utf8');
    return YAML.parseDocument(src);
  } catch {
    return undefined;
  }
}

/** Save Document to path. */
async function saveDoc(filePath: string, doc: TableDoc): Promise<void> {
  const text = doc.toString();
  await fs.mkdir(resolve(filePath, '..'), { recursive: true });
  await fs.writeFile(filePath, text, 'utf8');
}

/**
 * Compose a new table.yml using optional baseline and generated sections.
 * Preserves baseline Properties and inserts generated nodes.
 */
export async function composeNewTableYaml(
  outPath: string,
  baselinePath: string | undefined,
  generated: GeneratedSections,
  overlays?: OverlayOptions,
  managed?: ManagedTablePropertiesInfo,
): Promise<void> {
  const doc =
    (baselinePath ? await loadDoc(baselinePath) : undefined) ??
    ensureTableDoc();

  // Ensure Type is correct and header present.
  doc.set('Type', 'AWS::DynamoDB::Table');
  doc.commentBefore = HEADER_COMMENT;

  // Insert/replace generated sections
  if (generated.AttributeDefinitions)
    setPropsChild(doc, 'AttributeDefinitions', generated.AttributeDefinitions);
  if (generated.KeySchema) setPropsChild(doc, 'KeySchema', generated.KeySchema);
  if (generated.GlobalSecondaryIndexes)
    setPropsChild(
      doc,
      'GlobalSecondaryIndexes',
      generated.GlobalSecondaryIndexes,
    );

  // Optional overlays for initial composition
  if (overlays?.BillingMode)
    setPropsChild(doc, 'BillingMode', overlays.BillingMode);
  if (overlays?.ProvisionedThroughput)
    setPropsChild(doc, 'ProvisionedThroughput', overlays.ProvisionedThroughput);
  if (overlays?.TableName) setPropsChild(doc, 'TableName', overlays.TableName);

  applyManagedTableProperties(doc, managed);

  await saveDoc(outPath, doc);
}

/**
 * Refresh an existing table.yml in place: overwrite only generated nodes; preserve all comments/other properties.
 */
export async function refreshGeneratedSectionsInPlace(
  tablePath: string,
  generated: GeneratedSections,
  managed?: ManagedTablePropertiesInfo,
): Promise<void> {
  const doc = (await loadDoc(tablePath)) ?? ensureTableDoc();
  doc.set('Type', 'AWS::DynamoDB::Table');
  doc.commentBefore = doc.commentBefore ?? HEADER_COMMENT;

  if (generated.AttributeDefinitions)
    setPropsChild(doc, 'AttributeDefinitions', generated.AttributeDefinitions);
  if (generated.KeySchema) setPropsChild(doc, 'KeySchema', generated.KeySchema);
  if (generated.GlobalSecondaryIndexes)
    setPropsChild(
      doc,
      'GlobalSecondaryIndexes',
      generated.GlobalSecondaryIndexes,
    );

  applyManagedTableProperties(doc, managed);

  await saveDoc(tablePath, doc);
}

/**
 * Compute generated sections from an EntityManager (tables utility).
 */
export function computeGeneratedSections<C extends BaseConfigMap>(
  em: EntityManager<C>,
): GeneratedSections {
  const def = generateTableDefinition(em);
  return {
    AttributeDefinitions: def.AttributeDefinitions,
    KeySchema: def.KeySchema,
    GlobalSecondaryIndexes: def.GlobalSecondaryIndexes,
  };
}
