/**
 * Comment-preserving YAML refresh for DynamoDB table definitions.
 *
 * Requirements addressed:
 * - Preserve all non-generated Properties and comments in tables/NNN/table.yml.
 * - Overwrite only the generated sections:
 *   • Properties.AttributeDefinitions
 *   • Properties.KeySchema
 *   • Properties.GlobalSecondaryIndexes
 * - Compose a new table.yml from baseline when no file exists yet.
 */

import { promises as fs } from 'node:fs';
import { resolve } from 'node:path';

import type { CreateTableCommandInput } from '@aws-sdk/client-dynamodb';
import type {
  BaseConfigMap,
  EntityManager,
} from '@karmaniverous/entity-manager';
import YAML, { type Document, type YAMLMap } from 'yaml';

import { generateTableDefinition } from '../Tables/generateTableDefinition';

type TableDoc = Document;

const HEADER_COMMENT = [
  'GENERATED SECTIONS WARNING',
  '',
  '- The following Properties keys are regenerated by tooling:',
  '  • AttributeDefinitions',
  '  • KeySchema',
  '  • GlobalSecondaryIndexes',
  '',
  '- Edit non-generated Properties (e.g., BillingMode, TTL, PITR, Streams, SSE, Tags) in this file',
  '  or in tables/table.template.yml and re-run generate-table-definition.',
  '',
  '- Use validate-table-definition to detect drift against the EntityManager config.',
].join('\n');

function ensureTableDoc(): TableDoc {
  const doc = new YAML.Document();
  doc.commentBefore = HEADER_COMMENT;
  doc.set('Type', 'AWS::DynamoDB::Table');
  doc.set('Properties', {});
  return doc;
}

function getPropsNode(doc: TableDoc): YAMLMap {
  let props = doc.get('Properties');
  // Reset to an empty mapping if missing/unexpected
  if (
    !props ||
    typeof props !== 'object' ||
    !('set' in (props as Record<string, unknown>))
  ) {
    doc.set('Properties', {});
    props = doc.get('Properties');
  }
  return props as YAMLMap;
}

/** Replace a child under Properties (preserving other nodes/comments). */
function setPropsChild(doc: TableDoc, key: string, value: unknown) {
  const props = getPropsNode(doc);
  // The doc API preserves sibling nodes and their comments automatically.
  // We only replace the specified key.
  props.set(String(key), value);
}

export interface GeneratedSections {
  AttributeDefinitions?: CreateTableCommandInput['AttributeDefinitions'];
  KeySchema?: CreateTableCommandInput['KeySchema'];
  GlobalSecondaryIndexes?: CreateTableCommandInput['GlobalSecondaryIndexes'];
}

export interface OverlayOptions {
  /** Optional BillingMode for initial composition (no-op on refresh unless caller wants to change it). */
  BillingMode?: CreateTableCommandInput['BillingMode'];
  /** Provisioned throughput (RCU/WCU) if using PROVISIONED (initial composition helper). */
  ProvisionedThroughput?: CreateTableCommandInput['ProvisionedThroughput'];
  /** Optional one-off TableName override for creation-time plumbing (not persisted here). */
  TableName?: string;
}

/** Load YAML as a CST-backed Document if file exists; otherwise return undefined. */
async function loadDoc(filePath: string): Promise<TableDoc | undefined> {
  try {
    const src = await fs.readFile(filePath, 'utf8');
    return YAML.parseDocument(src);
  } catch {
    return undefined;
  }
}

/** Save Document to path. */
async function saveDoc(filePath: string, doc: TableDoc): Promise<void> {
  const text = doc.toString();
  await fs.mkdir(resolve(filePath, '..'), { recursive: true });
  await fs.writeFile(filePath, text, 'utf8');
}

/**
 * Compose a new table.yml using optional baseline and generated sections.
 * Preserves baseline Properties and inserts generated nodes.
 */
export async function composeNewTableYaml(
  outPath: string,
  baselinePath: string | undefined,
  generated: GeneratedSections,
  overlays?: OverlayOptions,
): Promise<void> {
  const doc =
    (baselinePath ? await loadDoc(baselinePath) : undefined) ??
    ensureTableDoc();

  // Ensure Type is correct and header present.
  doc.set('Type', 'AWS::DynamoDB::Table');
  doc.commentBefore = HEADER_COMMENT;

  // Insert/replace generated sections
  if (generated.AttributeDefinitions)
    setPropsChild(doc, 'AttributeDefinitions', generated.AttributeDefinitions);
  if (generated.KeySchema) setPropsChild(doc, 'KeySchema', generated.KeySchema);
  if (generated.GlobalSecondaryIndexes)
    setPropsChild(
      doc,
      'GlobalSecondaryIndexes',
      generated.GlobalSecondaryIndexes,
    );

  // Optional overlays for initial composition
  if (overlays?.BillingMode)
    setPropsChild(doc, 'BillingMode', overlays.BillingMode);
  if (overlays?.ProvisionedThroughput)
    setPropsChild(doc, 'ProvisionedThroughput', overlays.ProvisionedThroughput);
  if (overlays?.TableName) setPropsChild(doc, 'TableName', overlays.TableName);

  await saveDoc(outPath, doc);
}

/**
 * Refresh an existing table.yml in place: overwrite only generated nodes; preserve all comments/other properties.
 */
export async function refreshGeneratedSectionsInPlace(
  tablePath: string,
  generated: GeneratedSections,
): Promise<void> {
  const doc = (await loadDoc(tablePath)) ?? ensureTableDoc();
  doc.set('Type', 'AWS::DynamoDB::Table');
  doc.commentBefore = doc.commentBefore ?? HEADER_COMMENT;

  if (generated.AttributeDefinitions)
    setPropsChild(doc, 'AttributeDefinitions', generated.AttributeDefinitions);
  if (generated.KeySchema) setPropsChild(doc, 'KeySchema', generated.KeySchema);
  if (generated.GlobalSecondaryIndexes)
    setPropsChild(
      doc,
      'GlobalSecondaryIndexes',
      generated.GlobalSecondaryIndexes,
    );

  await saveDoc(tablePath, doc);
}

/**
 * Compute generated sections from an EntityManager (tables utility).
 */
export function computeGeneratedSections<C extends BaseConfigMap>(
  em: EntityManager<C>,
): GeneratedSections {
  const def = generateTableDefinition(em);
  return {
    AttributeDefinitions: def.AttributeDefinitions,
    KeySchema: def.KeySchema,
    GlobalSecondaryIndexes: def.GlobalSecondaryIndexes,
  };
}
